### ISSUE TITLE
Example contains commercial license code

### ISSUE THREAD

**Issue by fuglede** [flowty/flowty#3]
The [example given on this page](https://docs.flowty.ai/examples/tcmcf_linerlib/) currently provides a pair of `user`/`key` that resolves to a commercial license upon optimization:

```
In [4]: m.optimize()
Flowty Network Optimization Solver (version: 1.0.0)
License        : Commercial license
User           : customer
Expiration Date: Thu Dec 31 23:59:59 2020 GMT
```

Given that there's an unused pair of `user`/`key` sitting above it, this seems like it is unintended.

**Comment by spoorendonk** [comment]
Auch. Thanks
