### ISSUE TITLE
CG data

### ISSUE THREAD

**Issue by AGMA71997** [flowty/flowty#5]
Hey,

I am currently investigating the possibility of building a machine learning model to solve the pricing problem in VRPTW. This requires data on the problem itself. Would it be possible to use flowty to collect this data from its CG iterations? I know flowty solves the problem as a whole but I would be very interested in the output of every CG iteration (or at least the dual values from each iteration). 
Kindly let me know if this would be easily possible.

Regards,
Abdo

**Comment by BearMcBearface** [comment]
Hi Abdo

Sorry for the late reply.
Thank your for your suggestion. We will put on our todo-list the possibility of reporting the dual values in the log.

Best regards
Bjørn
